copy_file:
	cd build-MyTouristManager-Desktop_Qt_6_5_1_MinGW_64_bit-Release && \
    copy TourismCompass.exe ..\Ejecutable\TourismCompass.exe 

open_qt_creator:
    start "" "C:\Qt\6.5.1\mingw_64"

.PHONY: copy_file  open_qt_creator